server:
  port: 8084

spring:
  profiles:
    active: sdk
  application:
    name: PromoService

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:myStrongPassword}

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: promo-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
      schema:
        registry:
          url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >-
          leaderboard_event:com.company.promo.service.leaderboard.LeaderboardEvent,
          game_event:com.company.promobridge.GameEvent,
          tournament_event:com.company.promobridge.TournamentEvent
        schema:
          registry:
            url: http://localhost:8081

myapp:
  kafka:
    game-events:
      topic: "game.events"
      concurrency: 3
    tournament-events:
      topic: "tournament.events"
      concurrency: 3
    leaderboard-events:
      topic: "leaderboard.events"
      concurrency: 3


promo:
  service:
    leaderboard:
      update:
        rate:
          ms: 10000
